In [48]:
import mne
dir = "E:/ChristianMusaeus/Data/Eyes_closed_marked"
data_open = mne.io.read_epochs_eeglab(f"{dir}/10002_p01_epoched_EyesOpen_marked.set",verbose=False)
data_closed = mne.io.read_epochs_eeglab(f"{dir}/10002_p01_epoched_60EpochsMarked.set",verbose=False)

print(f"shape of data_open: {data_open.get_data().shape}")
print(f"data_open.info: {data_open.info}")
print(data_open.get_data())


shape of data_open: (1807, 19, 200)
data_open.info: <Info | 8 non-empty values
 bads: []
 ch_names: Fp1, Fp2, F3, F4, C3, C4, P3, P4, O1, O2, F7, F8, T7, T8, P7, ...
 chs: 19 EEG
 custom_ref_applied: False
 dig: 22 items (3 Cardinal, 19 EEG)
 highpass: 0.0 Hz
 lowpass: 100.0 Hz
 meas_date: unspecified
 nchan: 19
 projs: []
 sfreq: 200.0 Hz
>
[[[ 1.64877949e-05  2.87838593e-05  4.11144485e-05 ... -2.77062798e-05
   -2.84576168e-05 -3.02818871e-05]
  [ 2.33658733e-05  2.39724369e-05  2.53120117e-05 ... -2.38275204e-05
   -3.03160877e-05 -3.73518410e-05]
  [ 5.56208789e-07  1.94197865e-05  3.55472527e-05 ... -4.40262604e-06
   -5.13935518e-06 -4.33692741e-06]
  ...
  [-5.26981688e-06 -9.60867786e-06 -9.47003651e-06 ... -1.68589330e-06
   -1.65755904e-06 -1.20597713e-07]
  [-6.79857111e-06 -5.90761042e-06 -2.21324587e-06 ... -1.72749674e-06
    8.45716715e-07  4.93940067e-06]
  [-8.79035854e-06 -1.35151548e-05 -1.66151600e-05 ...  2.63907552e-06
    4.72407341e-06  9.29118729e-06]]

 [[-3.

In [46]:
import pandas as pd
import numpy as np
import h5py

hf = h5py.File(f"{dir}/eyesclosedmarked.mat", "r")
print(hf.keys())
print(hf["files"])
# extract data from files group

df = pd.DataFrame(hf["data"][:]).T
print(df.head())
print(df.shape)


# # Convert to a pandas dataframe
# data = np.array(new_data).T
# print(df.head())


<KeysViewHDF5 ['#refs#', '#subsystem#', 'EEG', 'data', 'files', 'ii']>
<HDF5 group "/files" (6 members)>
   0     1     2     3     4     5     6     7     8     9     ...  5593  \
0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...   0.0   
1   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...   0.0   
2   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...   0.0   
3   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...   0.0   
4   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...   0.0   

   5594  5595  5596  5597  5598  5599  5600  5601  5602  
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 5603 columns]
(80, 5603)


In [76]:
import mne
import os

newdata = []
dir = "E:/ChristianMusaeus/Data/Eyes_closed_marked"
for i in range(10002, 10213 + 1):
    file_name = f"{i}_p01_epoched_60EpochsMarked.set"
    if os.path.isfile(os.path.join(dir, file_name)):
        data = mne.io.read_epochs_eeglab(f"{dir}/{file_name}",verbose=False)
        newdata.append(data.get_data())
print(len(newdata))
print(newdata[0].shape)
print(newdata[1].shape)






80
(1807, 19, 200)
(1352, 19, 200)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (80,) + inhomogeneous part.

(1, 1807, 3800)


In [69]:
#save newdata as a pickle file
import pickle

with open(f"{dir}/Eyesclosed.pkl", "wb") as f:
    pickle.dump(df, f)
    print(f"{dir}/dataframe.pkl saved")


E:/ChristianMusaeus/Data/Eyes_closed_marked/dataframe.pkl saved


In [80]:
import numpy as np
#collapse second dimension for each array in newdata

empty = np.array([])

for aray in newdata:
    aray = np.reshape(aray, (aray.shape[0], aray.shape[1] * aray.shape[2]))     
    #append as a row to empty
    empty = np.vstack((empty, aray)) if empty.size else aray
print(empty.shape)
    






(189108, 3800)


In [26]:
data_open.info
print(data_open.annotations)
import numpy as np
unique_events = np.unique(data_closed.events[:, 2])
print("Unique event codes:", unique_events)



None
Unique event codes: [1]


In [31]:
print(data_closed.get_data().shape)
print(data_open.get_data().shape)
# print(data_closed.get_data([0,3]))
print(data_closed)
labels = data_closed.events[:5]
print(labels)

(1352, 19, 200)
(1807, 19, 200)
<EpochsEEGLAB | 1352 events (all good), 0 – 0.995 s (baseline off), ~39.2 MB, data loaded,
 'empty': 1352>
[[  1   0   1]
 [201   0   1]
 [401   0   1]
 [601   0   1]
 [801   0   1]]


In [28]:
# print the first 5 events
# print(data.events[:5])
# print(data_closed.events[150:200])
for event in data_closed.events:
    print(round(event[0]/200 * 256) - 1)
    print(event)
    # print(event)


0
[1 0 1]
256
[201   0   1]
512
[401   0   1]
768
[601   0   1]
1024
[801   0   1]
1280
[1001    0    1]
1536
[1201    0    1]
1792
[1401    0    1]
2048
[1601    0    1]
2304
[1801    0    1]
2560
[2001    0    1]
2816
[2201    0    1]
3072
[2401    0    1]
3328
[2601    0    1]
3584
[2801    0    1]
3840
[3001    0    1]
4096
[3201    0    1]
4352
[3401    0    1]
4608
[3601    0    1]
4864
[3801    0    1]
5120
[4001    0    1]
5376
[4201    0    1]
5632
[4401    0    1]
5888
[4601    0    1]
6144
[4801    0    1]
6400
[5001    0    1]
6656
[5201    0    1]
6912
[5401    0    1]
7168
[5601    0    1]
7424
[5801    0    1]
7680
[6001    0    1]
7936
[6201    0    1]
8192
[6401    0    1]
8448
[6601    0    1]
8704
[6801    0    1]
8960
[7001    0    1]
9216
[7201    0    1]
9472
[7401    0    1]
9728
[7601    0    1]
9984
[7801    0    1]
10240
[8001    0    1]
10496
[8201    0    1]
10752
[8401    0    1]
11008
[8601    0    1]
11264
[8801    0    1]
11520
[9001    0    1]
11776
[92

In [33]:
# open .mat file "10002.mat"
import scipy.io
import numpy as np
mat = scipy.io.loadmat(f"{dir}/10002.mat")
data = mat['EEG']['data'][0][0]
print(data.shape)



(25, 462592)


In [37]:
print(462592/256)
# Sampling rate is 256Hz. Shape of raw data is 25 x 462529.

(25, 462592)
1807.0


In [47]:
# print(mat['EEG'][:1][-10:])
# print "names of the channels"
""" we want 'Fp1' 'Fp2' 'F3' 'F4' 'C3' 'C4' 'P3 'P4' 'O1' 'O2' 'F7' 'F8' 'T7' 'T8' 'P7' 'P8' 'Fz' 'Cz' 'Pz' """
data = data[:19,:]
print(data.shape)



(19, 462592)
30.116666666666667
